// ============================================================================
// Built-in Code-Native Professional Certificate Templates
// 8 original, code-native templates matching institutional standards
// ============================================================================

import { CustomTemplate } from '@/types/template';

export const BUILT_IN_TEMPLATES: CustomTemplate[] = [
  // -------------------------------------------------------------------------
  // 1. Institutional Appreciation (Full 10-layer institutional reference structure)
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-institutional-appreciation',
    name: 'Institutional Appreciation',
    description: 'A4 Landscape institutional certificate featuring multi-logo header, event heading, subtitle, recipient name, segmented underline, wording, watermarks, 5 signatories, QR token, and certificate code.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FAFAF8',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      // Layer 1: Outer Dark Frame & Safe Margins
      {
        id: 'inst-outer-border',
        type: 'border',
        name: 'Outer Dark Frame',
        x: 18,
        y: 18,
        width: 806,
        height: 559,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: true,
        opacity: 1,
        borderStyle: {
          borderType: 'solid',
          color: '#1E293B',
          width: 2.5,
          cornerRadius: 2,
        },
      },
      {
        id: 'inst-inner-border',
        type: 'border',
        name: 'Inner Accent Line',
        x: 24,
        y: 24,
        width: 794,
        height: 547,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: true,
        opacity: 1,
        borderStyle: {
          borderType: 'solid',
          color: '#3B82F6',
          width: 0.75,
          cornerRadius: 0,
        },
      },

      // Layer 2: Institution Header (Centre Name, Affiliation, Accreditation)
      {
        id: 'inst-header-name',
        type: 'dynamic-text',
        name: 'Institution Name',
        x: 120,
        y: 35,
        width: 602,
        height: 28,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{organization.name}}',
        fallbackValue: 'ABC ENGINEERING COLLEGE',
        textStyle: {
          fontSize: 20,
          fontFamily: 'Helvetica',
          fontWeight: 'bold',
          fontStyle: 'normal',
          fill: '#0F172A',
          align: 'center',
          textTransform: 'uppercase',
          letterSpacing: 1.5,
        },
      },
      {
        id: 'inst-header-affiliation',
        type: 'dynamic-text',
        name: 'Affiliation Statement',
        x: 100,
        y: 65,
        width: 642,
        height: 16,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{organization.affiliation}}',
        fallbackValue: 'Autonomous Institution Affiliated to State Technological University',
        textStyle: {
          fontSize: 10,
          fontFamily: 'Helvetica',
          fontWeight: 'normal',
          fontStyle: 'normal',
          fill: '#475569',
          align: 'center',
        },
      },
      {
        id: 'inst-header-accreditation',
        type: 'dynamic-text',
        name: 'Accreditation Statement',
        x: 100,
        y: 81,
        width: 642,
        height: 14,
        rotation: 0,
        zIndex: 5,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{organization.accreditation}}',
        fallbackValue: 'Accredited with NAAC A+ Grade & NBA | ISO 9001:2015 Certified',
        textStyle: {
          fontSize: 9,
          fontFamily: 'Helvetica',
          fontWeight: 'normal',
          fontStyle: 'italic',
          fill: '#64748B',
          align: 'center',
        },
      },

      // Layer 3: Event Heading
      {
        id: 'inst-event-heading',
        type: 'dynamic-text',
        name: 'Event Heading',
        x: 80,
        y: 108,
        width: 682,
        height: 28,
        rotation: 0,
        zIndex: 6,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{event.name}}',
        fallbackValue: 'SOFTWARE INNOVATION CHALLENGE 2026',
        textStyle: {
          fontSize: 18,
          fontFamily: 'Helvetica',
          fontWeight: 'bold',
          fontStyle: 'normal',
          fill: '#1E40AF',
          align: 'center',
          textTransform: 'uppercase',
          letterSpacing: 2,
        },
      },

      // Layer 4: Certificate Title & Subtitle
      {
        id: 'inst-cert-title',
        type: 'text',
        name: 'Certificate Main Title',
        x: 100,
        y: 145,
        width: 642,
        height: 42,
        rotation: 0,
        zIndex: 7,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE',
        textStyle: {
          fontSize: 36,
          fontFamily: 'Georgia',
          fontWeight: 'bold',
          fontStyle: 'normal',
          fill: '#0F172A',
          align: 'center',
          letterSpacing: 4,
        },
      },
      {
        id: 'inst-cert-subtitle',
        type: 'dynamic-text',
        name: 'Certificate Subtitle',
        x: 150,
        y: 188,
        width: 542,
        height: 22,
        rotation: 0,
        zIndex: 8,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{certificate.type}}',
        fallbackValue: 'OF APPRECIATION',
        textStyle: {
          fontSize: 14,
          fontFamily: 'Helvetica',
          fontWeight: 'bold',
          fontStyle: 'normal',
          fill: '#2563EB',
          align: 'center',
          letterSpacing: 3,
        },
      },

      // Layer 5: Recipient Name Focus
      {
        id: 'inst-presented-clause',
        type: 'text',
        name: 'Certifying Clause',
        x: 200,
        y: 222,
        width: 442,
        height: 18,
        rotation: 0,
        zIndex: 9,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'This is proudly presented to',
        textStyle: {
          fontSize: 11,
          fontFamily: 'Georgia',
          fontWeight: 'normal',
          fontStyle: 'italic',
          fill: '#64748B',
          align: 'center',
        },
      },
      {
        id: 'inst-recipient-name',
        type: 'dynamic-text',
        name: 'Recipient Full Name',
        x: 50,
        y: 245,
        width: 742,
        height: 48,
        rotation: 0,
        zIndex: 10,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        fallbackValue: 'SUBASH P',
        textStyle: {
          fontSize: 34,
          fontFamily: 'Georgia',
          fontWeight: 'bold',
          fontStyle: 'normal',
          fill: '#0F172A',
          align: 'center',
          textTransform: 'uppercase',
          letterSpacing: 1,
        },
      },

      // Layer 6: Segmented Underline Below Recipient Name
      {
        id: 'inst-underline-seg1',
        type: 'shape',
        name: 'Segmented Line Left',
        x: 271,
        y: 296,
        width: 120,
        height: 2,
        rotation: 0,
        zIndex: 11,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: {
          shapeType: 'line',
          fill: 'transparent',
          stroke: '#1E40AF',
          strokeWidth: 2,
        },
      },
      {
        id: 'inst-underline-center',
        type: 'shape',
        name: 'Center Accent Emblem',
        x: 411,
        y: 292,
        width: 20,
        height: 10,
        rotation: 0,
        zIndex: 12,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: {
          shapeType: 'rectangle',
          fill: '#D97706',
          stroke: 'transparent',
          strokeWidth: 0,
          cornerRadius: 2,
        },
      },
      {
        id: 'inst-underline-seg2',
        type: 'shape',
        name: 'Segmented Line Right',
        x: 451,
        y: 296,
        width: 120,
        height: 2,
        rotation: 0,
        zIndex: 13,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: {
          shapeType: 'line',
          fill: 'transparent',
          stroke: '#1E40AF',
          strokeWidth: 2,
        },
      },

      // Layer 7: Certificate Wording (Rich multi-line structure)
      {
        id: 'inst-wording-body',
        type: 'text',
        name: 'Appreciation Wording',
        x: 90,
        y: 315,
        width: 662,
        height: 55,
        rotation: 0,
        zIndex: 14,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'for outstanding participation and valuable contributions in the event organized by the Department of Computer Science, School of Computing, held from March 10-12, 2026.',
        textStyle: {
          fontSize: 12,
          fontFamily: 'Helvetica',
          fontWeight: 'normal',
          fontStyle: 'normal',
          fill: '#334155',
          align: 'center',
          lineHeight: 1.4,
        },
      },

      // Layer 9: 5 Signatory Columns Layout
      // Column 1
      {
        id: 'sig-col1-name',
        type: 'dynamic-text',
        name: 'Signatory 1 Name',
        x: 40,
        y: 475,
        width: 140,
        height: 18,
        rotation: 0,
        zIndex: 15,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.1.name}}',
        fallbackValue: 'Dr. R. Sundaram',
        textStyle: { fontSize: 11, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'sig-col1-desig',
        type: 'dynamic-text',
        name: 'Signatory 1 Designation',
        x: 40,
        y: 494,
        width: 140,
        height: 25,
        rotation: 0,
        zIndex: 16,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.1.designation}}',
        fallbackValue: 'Convener & Professor',
        textStyle: { fontSize: 9, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#64748B', align: 'center' },
      },

      // Column 2
      {
        id: 'sig-col2-name',
        type: 'dynamic-text',
        name: 'Signatory 2 Name',
        x: 195,
        y: 475,
        width: 140,
        height: 18,
        rotation: 0,
        zIndex: 17,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.2.name}}',
        fallbackValue: 'Dr. M. Lakshmi',
        textStyle: { fontSize: 11, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'sig-col2-desig',
        type: 'dynamic-text',
        name: 'Signatory 2 Designation',
        x: 195,
        y: 494,
        width: 140,
        height: 25,
        rotation: 0,
        zIndex: 18,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.2.designation}}',
        fallbackValue: 'Head of Department',
        textStyle: { fontSize: 9, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#64748B', align: 'center' },
      },

      // Column 3
      {
        id: 'sig-col3-name',
        type: 'dynamic-text',
        name: 'Signatory 3 Name',
        x: 351,
        y: 475,
        width: 140,
        height: 18,
        rotation: 0,
        zIndex: 19,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.3.name}}',
        fallbackValue: 'Prof. V. Anand',
        textStyle: { fontSize: 11, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'sig-col3-desig',
        type: 'dynamic-text',
        name: 'Signatory 3 Designation',
        x: 351,
        y: 494,
        width: 140,
        height: 25,
        rotation: 0,
        zIndex: 20,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.3.designation}}',
        fallbackValue: 'Dean of Academics',
        textStyle: { fontSize: 9, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#64748B', align: 'center' },
      },

      // Column 4
      {
        id: 'sig-col4-name',
        type: 'dynamic-text',
        name: 'Signatory 4 Name',
        x: 507,
        y: 475,
        width: 140,
        height: 18,
        rotation: 0,
        zIndex: 21,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.4.name}}',
        fallbackValue: 'Dr. S. K. Verma',
        textStyle: { fontSize: 11, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'sig-col4-desig',
        type: 'dynamic-text',
        name: 'Signatory 4 Designation',
        x: 507,
        y: 494,
        width: 140,
        height: 25,
        rotation: 0,
        zIndex: 22,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.4.designation}}',
        fallbackValue: 'Registrar',
        textStyle: { fontSize: 9, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#64748B', align: 'center' },
      },

      // Column 5
      {
        id: 'sig-col5-name',
        type: 'dynamic-text',
        name: 'Signatory 5 Name',
        x: 662,
        y: 475,
        width: 140,
        height: 18,
        rotation: 0,
        zIndex: 23,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.5.name}}',
        fallbackValue: 'Dr. K. Parthasarathy',
        textStyle: { fontSize: 11, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'sig-col5-desig',
        type: 'dynamic-text',
        name: 'Signatory 5 Designation',
        x: 662,
        y: 494,
        width: 140,
        height: 25,
        rotation: 0,
        zIndex: 24,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.5.designation}}',
        fallbackValue: 'Principal',
        textStyle: { fontSize: 9, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#64748B', align: 'center' },
      },

      // Signature line dividers
      {
        id: 'sig-line-1',
        type: 'shape',
        name: 'Sig 1 Line',
        x: 50,
        y: 468,
        width: 120,
        height: 1,
        rotation: 0,
        zIndex: 25,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#CBD5E1', strokeWidth: 1 },
      },
      {
        id: 'sig-line-2',
        type: 'shape',
        name: 'Sig 2 Line',
        x: 205,
        y: 468,
        width: 120,
        height: 1,
        rotation: 0,
        zIndex: 26,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#CBD5E1', strokeWidth: 1 },
      },
      {
        id: 'sig-line-3',
        type: 'shape',
        name: 'Sig 3 Line',
        x: 361,
        y: 468,
        width: 120,
        height: 1,
        rotation: 0,
        zIndex: 27,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#CBD5E1', strokeWidth: 1 },
      },
      {
        id: 'sig-line-4',
        type: 'shape',
        name: 'Sig 4 Line',
        x: 517,
        y: 468,
        width: 120,
        height: 1,
        rotation: 0,
        zIndex: 28,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#CBD5E1', strokeWidth: 1 },
      },
      {
        id: 'sig-line-5',
        type: 'shape',
        name: 'Sig 5 Line',
        x: 672,
        y: 468,
        width: 120,
        height: 1,
        rotation: 0,
        zIndex: 29,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#CBD5E1', strokeWidth: 1 },
      },

      // Layer 10: Security Footer & QR Code
      {
        id: 'inst-qr-code',
        type: 'qr',
        name: 'Verification QR Token',
        x: 35,
        y: 505,
        width: 55,
        height: 55,
        rotation: 0,
        zIndex: 30,
        visible: true,
        locked: false,
        opacity: 1,
        qrStyle: { size: 55, fgColor: '#0F172A', bgColor: '#FFFFFF', displayCodeLabel: false },
      },
      {
        id: 'inst-cert-code-label',
        type: 'certificate-code',
        name: 'Certificate ID Code',
        x: 550,
        y: 545,
        width: 250,
        height: 18,
        rotation: 0,
        zIndex: 31,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{certificate.code}}',
        fallbackValue: 'ID: CERT-2026-INST-0842',
        textStyle: { fontSize: 9, fontFamily: 'Courier New', fontWeight: 'bold', fontStyle: 'normal', fill: '#64748B', align: 'right' },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 2. Academic Participation
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-academic-participation',
    name: 'Academic Participation',
    description: 'Classic double-bordered academic layout for conferences and symposiums.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFFFF',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'acad-border',
        type: 'border',
        name: 'Double Border',
        x: 20,
        y: 20,
        width: 802,
        height: 555,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: true,
        opacity: 1,
        borderStyle: { borderType: 'double', color: '#1E3A8A', width: 4 },
      },
      {
        id: 'acad-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 80,
        width: 642,
        height: 50,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF PARTICIPATION',
        textStyle: { fontSize: 30, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#1E3A8A', align: 'center', letterSpacing: 2 },
      },
      {
        id: 'acad-clause',
        type: 'text',
        name: 'Clause',
        x: 150,
        y: 160,
        width: 542,
        height: 20,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'This certificate is awarded to',
        textStyle: { fontSize: 12, fontFamily: 'Georgia', fontWeight: 'normal', fontStyle: 'italic', fill: '#64748B', align: 'center' },
      },
      {
        id: 'acad-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 100,
        y: 195,
        width: 642,
        height: 45,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 32, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'acad-wording',
        type: 'text',
        name: 'Wording',
        x: 120,
        y: 260,
        width: 602,
        height: 60,
        rotation: 0,
        zIndex: 5,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'for actively participating in the National Academic Conference & Workshop on Advanced Engineering Principles.',
        textStyle: { fontSize: 13, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#334155', align: 'center', lineHeight: 1.4 },
      },
      {
        id: 'acad-sig1',
        type: 'dynamic-text',
        name: 'Signatory 1',
        x: 120,
        y: 470,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 6,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.1.name}}',
        fallbackValue: 'Dr. R. Sundaram',
        textStyle: { fontSize: 12, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'acad-sig2',
        type: 'dynamic-text',
        name: 'Signatory 2',
        x: 522,
        y: 470,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 7,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{signatory.2.name}}',
        fallbackValue: 'Dr. M. Lakshmi',
        textStyle: { fontSize: 12, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'acad-qr',
        type: 'qr',
        name: 'QR Code',
        x: 730,
        y: 480,
        width: 70,
        height: 70,
        rotation: 0,
        zIndex: 8,
        visible: true,
        locked: false,
        opacity: 1,
        qrStyle: { size: 70, fgColor: '#1E3A8A', bgColor: '#FFFFFF', displayCodeLabel: false },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 3. Training Completion
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-training-completion',
    name: 'Training Completion',
    description: 'Clean modern corporate theme for professional development & skill courses.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#F8FAFC',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'train-banner',
        type: 'shape',
        name: 'Left Accent Banner',
        x: 0,
        y: 0,
        width: 24,
        height: 595,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: true,
        opacity: 1,
        shapeStyle: { shapeType: 'rectangle', fill: '#0EA5E9', stroke: 'transparent', strokeWidth: 0 },
      },
      {
        id: 'train-title',
        type: 'text',
        name: 'Title',
        x: 80,
        y: 60,
        width: 682,
        height: 40,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF COMPLETION',
        textStyle: { fontSize: 28, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'left', letterSpacing: 2 },
      },
      {
        id: 'train-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 80,
        y: 170,
        width: 682,
        height: 45,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 32, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0EA5E9', align: 'left' },
      },
      {
        id: 'train-wording',
        type: 'text',
        name: 'Wording',
        x: 80,
        y: 240,
        width: 600,
        height: 60,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'has successfully completed the Intensive Professional Training Program on Modern Full-Stack Web Development & Cloud Architecture.',
        textStyle: { fontSize: 13, fontFamily: 'Helvetica', fontWeight: 'normal', fontStyle: 'normal', fill: '#475569', align: 'left', lineHeight: 1.5 },
      },
      {
        id: 'train-qr',
        type: 'qr',
        name: 'QR Code',
        x: 720,
        y: 470,
        width: 75,
        height: 75,
        rotation: 0,
        zIndex: 5,
        visible: true,
        locked: false,
        opacity: 1,
        qrStyle: { size: 75, fgColor: '#0F172A', bgColor: '#FFFFFF', displayCodeLabel: true },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 4. Achievement Award
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-achievement-award',
    name: 'Achievement Award',
    description: 'Gold accent borders and high-contrast typography for honors and competitions.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFFFF',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'achieve-border',
        type: 'border',
        name: 'Gold Border',
        x: 20,
        y: 20,
        width: 802,
        height: 555,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: true,
        opacity: 1,
        borderStyle: { borderType: 'solid', color: '#D97706', width: 3 },
      },
      {
        id: 'achieve-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 70,
        width: 642,
        height: 50,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF ACHIEVEMENT',
        textStyle: { fontSize: 32, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#B45309', align: 'center', letterSpacing: 3 },
      },
      {
        id: 'achieve-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 80,
        y: 190,
        width: 682,
        height: 48,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 34, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
      {
        id: 'achieve-qr',
        type: 'qr',
        name: 'QR Code',
        x: 730,
        y: 480,
        width: 70,
        height: 70,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        qrStyle: { size: 70, fgColor: '#B45309', bgColor: '#FFFFFF', displayCodeLabel: false },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 5. Internship Completion
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-internship-completion',
    name: 'Internship Completion',
    description: 'Corporate internship certificate with dual signatory columns and verification code.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFFFF',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'intern-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 75,
        width: 642,
        height: 40,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'INTERNSHIP COMPLETION CERTIFICATE',
        textStyle: { fontSize: 26, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#1E40AF', align: 'center', letterSpacing: 2 },
      },
      {
        id: 'intern-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 100,
        y: 190,
        width: 642,
        height: 45,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 30, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 6. Corporate Recognition
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-corporate-recognition',
    name: 'Corporate Recognition',
    description: 'Dark slate minimalist executive recognition certificate.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#0F172A',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'corp-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 80,
        width: 642,
        height: 45,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF RECOGNITION',
        textStyle: { fontSize: 28, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#38BDF8', align: 'center', letterSpacing: 3 },
      },
      {
        id: 'corp-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 100,
        y: 200,
        width: 642,
        height: 48,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 34, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#F8FAFC', align: 'center' },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 7. Workshop Participation
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-workshop-participation',
    name: 'Workshop Participation',
    description: 'Modern workshop & technical bootcamp certificate format.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFFFF',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'work-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 70,
        width: 642,
        height: 40,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'WORKSHOP PARTICIPATION CERTIFICATE',
        textStyle: { fontSize: 26, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#2563EB', align: 'center', letterSpacing: 2 },
      },
      {
        id: 'work-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 100,
        y: 190,
        width: 642,
        height: 45,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 32, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
    ],
  },

  // -------------------------------------------------------------------------
  // 8. Competition Winner
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-competition-winner',
    name: 'Competition Winner',
    description: 'High-honor competition award certificate with rank badge and gold theme.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFBEB',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      {
        id: 'win-border',
        type: 'border',
        name: 'Outer Gold Border',
        x: 18,
        y: 18,
        width: 806,
        height: 559,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: true,
        opacity: 1,
        borderStyle: { borderType: 'solid', color: '#D97706', width: 3 },
      },
      {
        id: 'win-title',
        type: 'text',
        name: 'Title',
        x: 100,
        y: 65,
        width: 642,
        height: 45,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF VICTORY',
        textStyle: { fontSize: 32, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#B45309', align: 'center', letterSpacing: 3 },
      },
      {
        id: 'win-rank',
        type: 'dynamic-text',
        name: 'Rank Badge',
        x: 346,
        y: 125,
        width: 150,
        height: 30,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.rank}}',
        fallbackValue: '1st PLACE WINNER',
        textStyle: { fontSize: 14, fontFamily: 'Helvetica', fontWeight: 'bold', fontStyle: 'normal', fill: '#D97706', align: 'center', textTransform: 'uppercase' },
      },
      {
        id: 'win-name',
        type: 'dynamic-text',
        name: 'Recipient Name',
        x: 80,
        y: 200,
        width: 682,
        height: 48,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        dynamicBinding: '{{recipient.name}}',
        textStyle: { fontSize: 34, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#0F172A', align: 'center' },
      },
    ],
  },
  // -------------------------------------------------------------------------
  // 9. Phase 2 Shape Showcase Test Template
  // -------------------------------------------------------------------------
  {
    id: 'tmpl-phase2-shape-showcase',
    name: 'Phase 2 Shape Showcase',
    description: 'Test certificate containing outer border, inner border, corner ornaments, dividers, decorative rings, star accents, triangle, polygon, and seal badge.',
    category: 'Built-in',
    orientation: 'landscape',
    width: 842,
    height: 595,
    backgroundColor: '#FFFFFF',
    isBuiltIn: true,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    elements: [
      // Outer Border
      {
        id: 'sh-outer-rect',
        type: 'shape',
        name: 'Outer Solid Border',
        x: 20,
        y: 20,
        width: 802,
        height: 555,
        rotation: 0,
        zIndex: 1,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'rectangle', fill: 'transparent', stroke: '#1E40AF', strokeWidth: 3, strokeStyle: 'solid' },
      },
      // Inner Dashed Border
      {
        id: 'sh-inner-rect',
        type: 'shape',
        name: 'Inner Dashed Border',
        x: 28,
        y: 28,
        width: 786,
        height: 539,
        rotation: 0,
        zIndex: 2,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'rounded-rectangle', fill: 'transparent', stroke: '#D97706', strokeWidth: 1.5, strokeStyle: 'dashed', cornerRadius: 8 },
      },
      // Corner Ornament Top Left
      {
        id: 'sh-corner-tl',
        type: 'shape',
        name: 'Corner Ornament Top Left',
        x: 35,
        y: 35,
        width: 50,
        height: 50,
        rotation: 0,
        zIndex: 3,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'rounded-rectangle', fill: 'transparent', stroke: '#B45309', strokeWidth: 2, cornerRadius: 4 },
      },
      // Corner Ornament Top Right
      {
        id: 'sh-corner-tr',
        type: 'shape',
        name: 'Corner Ornament Top Right',
        x: 757,
        y: 35,
        width: 50,
        height: 50,
        rotation: 0,
        zIndex: 4,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'rounded-rectangle', fill: 'transparent', stroke: '#B45309', strokeWidth: 2, cornerRadius: 4 },
      },
      // Accent Divider Line
      {
        id: 'sh-divider-main',
        type: 'shape',
        name: 'Main Accent Divider',
        x: 221,
        y: 125,
        width: 400,
        height: 2,
        rotation: 0,
        zIndex: 5,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#1E40AF', strokeWidth: 2, strokeStyle: 'solid' },
      },
      // Double Divider
      {
        id: 'sh-double-divider',
        type: 'shape',
        name: 'Subheading Double Divider',
        x: 271,
        y: 330,
        width: 300,
        height: 3,
        rotation: 0,
        zIndex: 6,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'line', fill: 'transparent', stroke: '#D97706', strokeWidth: 3, strokeStyle: 'dashed' },
      },
      // Decorative Circle Ring
      {
        id: 'sh-ring-center',
        type: 'shape',
        name: 'Decorative Ring Background',
        x: 361,
        y: 220,
        width: 120,
        height: 120,
        rotation: 0,
        zIndex: 7,
        visible: true,
        locked: false,
        opacity: 0.15,
        shapeStyle: { shapeType: 'circle', fill: 'transparent', stroke: '#1E40AF', strokeWidth: 4, strokeStyle: 'dotted' },
      },
      // Gold Star Accent
      {
        id: 'sh-gold-star',
        type: 'shape',
        name: 'Gold Star Accent',
        x: 396,
        y: 65,
        width: 50,
        height: 50,
        rotation: 0,
        zIndex: 8,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'star', fill: '#F59E0B', stroke: '#B45309', strokeWidth: 1, points: 5, innerRadiusRatio: 0.45 },
      },
      // Official Seal Badge
      {
        id: 'sh-seal-badge',
        type: 'shape',
        name: 'Official Seal Badge',
        x: 700,
        y: 440,
        width: 90,
        height: 90,
        rotation: 0,
        zIndex: 9,
        visible: true,
        locked: false,
        opacity: 1,
        shapeStyle: { shapeType: 'star', fill: '#B45309', stroke: '#F59E0B', strokeWidth: 2, points: 16, innerRadiusRatio: 0.85 },
      },
      // Triangle Accent
      {
        id: 'sh-triangle-accent',
        type: 'shape',
        name: 'Ribbon Triangle Accent',
        x: 50,
        y: 470,
        width: 60,
        height: 60,
        rotation: 0,
        zIndex: 10,
        visible: true,
        locked: false,
        opacity: 0.9,
        shapeStyle: { shapeType: 'triangle', fill: '#1E40AF', stroke: '#1E3A8A', strokeWidth: 1, strokeStyle: 'solid' },
      },
      // Polygon Hexagon
      {
        id: 'sh-polygon-hexagon',
        type: 'shape',
        name: 'Geometric Hexagon Accent',
        x: 120,
        y: 470,
        width: 60,
        height: 60,
        rotation: 0,
        zIndex: 11,
        visible: true,
        locked: false,
        opacity: 0.8,
        shapeStyle: { shapeType: 'polygon', fill: '#059669', stroke: '#047857', strokeWidth: 1, points: 6, strokeStyle: 'solid' },
      },
      // Certificate Title Text
      {
        id: 'sh-title-text',
        type: 'text',
        name: 'Certificate Header Text',
        x: 150,
        y: 135,
        width: 542,
        height: 40,
        rotation: 0,
        zIndex: 12,
        visible: true,
        locked: false,
        opacity: 1,
        textValue: 'CERTIFICATE OF EXCELLENCE',
        textStyle: { fontSize: 26, fontFamily: 'Georgia', fontWeight: 'bold', fontStyle: 'normal', fill: '#1E293B', align: 'center' },
      },
    ],
  },
];
