import { CustomTemplate, Orientation, TemplateElement } from '@/types/template';

export interface SmartDesignOptions {
  purpose: string;
  style: 'Modern' | 'Academic' | 'Elegant' | 'Corporate' | 'Minimal' | 'Traditional' | 'Creative';
  orientation: Orientation;
  primaryColor: string;
  secondaryColor: string;
  organizationType: string;
  signatoriesCount: 1 | 2;
  hasLogo: boolean;
  hasQrCode: boolean;
}

export interface TemplateDesignProvider {
  generateLayouts(options: SmartDesignOptions): Promise<CustomTemplate[]>;
}

export class LocalSmartDesignProvider implements TemplateDesignProvider {
  async generateLayouts(options: SmartDesignOptions): Promise<CustomTemplate[]> {
    const isLandscape = options.orientation === 'landscape';
    const width = isLandscape ? 842 : 595;
    const height = isLandscape ? 595 : 842;
    const centerX = width / 2;

    const pColor = options.primaryColor || '#0F172A';
    const sColor = options.secondaryColor || '#2563EB';

    // Variation 1: Centered Academic / Classic Layout
    const var1: CustomTemplate = {
      id: `tmpl-smart-1-${Date.now()}`,
      name: `${options.purpose} — Centered Classic`,
      description: `Generated by Smart Design Assistant (${options.style} style)`,
      category: 'Smart Design',
      orientation: options.orientation,
      width,
      height,
      backgroundColor: '#FFFFFF',
      version: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      elements: [
        // Outer Decorative Frame
        {
          id: 'elem-frame',
          type: 'shape',
          name: 'Outer Border',
          x: 20,
          y: 20,
          width: width - 40,
          height: height - 40,
          rotation: 0,
          zIndex: 1,
          visible: true,
          locked: false,
          opacity: 1,
          shapeStyle: {
            shapeType: 'rectangle',
            fill: 'transparent',
            stroke: pColor,
            strokeWidth: 3,
            cornerRadius: 4,
          },
        },
        // Institution Header
        {
          id: 'elem-org-name',
          type: 'dynamic-text',
          name: 'Organization Name',
          x: centerX - 300,
          y: 60,
          width: 600,
          height: 30,
          rotation: 0,
          zIndex: 2,
          visible: true,
          locked: false,
          opacity: 1,
          dynamicBinding: '{{organization.name}}',
          textStyle: {
            fontSize: 22,
            fontFamily: 'Helvetica',
            fontWeight: 'bold',
            fontStyle: 'normal',
            fill: pColor,
            align: 'center',
            textTransform: 'uppercase',
          },
        },
        // Certificate Main Title
        {
          id: 'elem-title',
          type: 'text',
          name: 'Certificate Title',
          x: centerX - 300,
          y: 110,
          width: 600,
          height: 45,
          rotation: 0,
          zIndex: 3,
          visible: true,
          locked: false,
          opacity: 1,
          textValue: 'CERTIFICATE OF ACHIEVEMENT',
          textStyle: {
            fontSize: 32,
            fontFamily: 'Georgia',
            fontWeight: 'bold',
            fontStyle: 'normal',
            fill: sColor,
            align: 'center',
            letterSpacing: 2,
          },
        },
        // Presented To
        {
          id: 'elem-presented-to',
          type: 'text',
          name: 'Presented To Label',
          x: centerX - 200,
          y: 175,
          width: 400,
          height: 20,
          rotation: 0,
          zIndex: 4,
          visible: true,
          locked: false,
          opacity: 1,
          textValue: 'THIS IS PROUDLY PRESENTED TO',
          textStyle: {
            fontSize: 11,
            fontFamily: 'Helvetica',
            fontWeight: 'bold',
            fontStyle: 'normal',
            fill: '#64748B',
            align: 'center',
            letterSpacing: 1.5,
          },
        },
        // Recipient Name Placeholder
        {
          id: 'elem-recipient-name',
          type: 'dynamic-text',
          name: 'Recipient Name',
          x: centerX - 350,
          y: 205,
          width: 700,
          height: 50,
          rotation: 0,
          zIndex: 5,
          visible: true,
          locked: false,
          opacity: 1,
          dynamicBinding: '{{recipient.name}}',
          textStyle: {
            fontSize: 36,
            fontFamily: 'Georgia',
            fontWeight: 'bold',
            fontStyle: 'normal',
            fill: pColor,
            align: 'center',
          },
        },
        // Course Description
        {
          id: 'elem-course-desc',
          type: 'dynamic-text',
          name: 'Course Description',
          x: centerX - 300,
          y: 275,
          width: 600,
          height: 40,
          rotation: 0,
          zIndex: 6,
          visible: true,
          locked: false,
          opacity: 1,
          dynamicBinding: '{{event.name}}',
          textStyle: {
            fontSize: 16,
            fontFamily: 'Helvetica',
            fontWeight: 'normal',
            fontStyle: 'normal',
            fill: '#334155',
            align: 'center',
          },
        },
        // Signatory 1
        {
          id: 'elem-signatory-name',
          type: 'dynamic-text',
          name: 'Signatory Name',
          x: options.signatoriesCount === 2 ? 100 : centerX - 120,
          y: height - 120,
          width: 240,
          height: 25,
          rotation: 0,
          zIndex: 7,
          visible: true,
          locked: false,
          opacity: 1,
          dynamicBinding: '{{signatory.name}}',
          textStyle: {
            fontSize: 14,
            fontFamily: 'Helvetica',
            fontWeight: 'bold',
            fontStyle: 'normal',
            fill: pColor,
            align: 'center',
          },
        },
        // QR Code
        ...(options.hasQrCode
          ? [
              {
                id: 'elem-qr',
                type: 'qr' as const,
                name: 'QR Code Verification',
                x: width - 110,
                y: height - 110,
                width: 80,
                height: 80,
                rotation: 0,
                zIndex: 8,
                visible: true,
                locked: false,
                opacity: 1,
                qrStyle: {
                  size: 80,
                  fgColor: pColor,
                  bgColor: '#FFFFFF',
                  displayCodeLabel: true,
                },
              },
            ]
          : []),
      ],
    };

    // Variation 2: Modern Side-Accent Layout
    const var2: CustomTemplate = {
      ...var1,
      id: `tmpl-smart-2-${Date.now()}`,
      name: `${options.purpose} — Modern Side Banner`,
      elements: [
        {
          id: 'elem-side-banner',
          type: 'shape',
          name: 'Side Banner',
          x: 0,
          y: 0,
          width: 40,
          height,
          rotation: 0,
          zIndex: 1,
          visible: true,
          locked: false,
          opacity: 1,
          shapeStyle: {
            shapeType: 'rectangle',
            fill: sColor,
            stroke: 'transparent',
            strokeWidth: 0,
          },
        },
        ...var1.elements.slice(1),
      ],
    };

    // Variation 3: Minimal Clean Layout
    const var3: CustomTemplate = {
      ...var1,
      id: `tmpl-smart-3-${Date.now()}`,
      name: `${options.purpose} — Minimal Clean`,
      backgroundColor: '#FAFAFA',
    };

    return [var1, var2, var3];
  }
}
